/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.9.0-SNAPSHOT).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.dyrnq.httpbin.api;

import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", comments = "Generator version: 7.9.0-SNAPSHOT")
@Validated
@Tag(name = "Response formats", description = "Returns responses in different data formats")
public interface ResponseFormatsApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * GET /brotli : Returns Brotli-encoded data.
     *
     * @return Brotli-encoded data. (status code 200)
     */
    @Operation(
        operationId = "brotliGet",
        summary = "Returns Brotli-encoded data.",
        tags = { "Response formats" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Brotli-encoded data.")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/brotli"
    )
    
    default ResponseEntity<Void> brotliGet(
        
    ) throws Exception {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /deflate : Returns Deflate-encoded data.
     *
     * @return Defalte-encoded data. (status code 200)
     */
    @Operation(
        operationId = "deflateGet",
        summary = "Returns Deflate-encoded data.",
        tags = { "Response formats" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Defalte-encoded data.")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/deflate"
    )
    
    default ResponseEntity<Void> deflateGet(
        
    ) throws Exception {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /deny : Returns page denied by robots.txt rules.
     *
     * @return Denied message (status code 200)
     */
    @Operation(
        operationId = "denyGet",
        summary = "Returns page denied by robots.txt rules.",
        tags = { "Response formats" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Denied message")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/deny"
    )
    
    default ResponseEntity<Void> denyGet(
        
    ) throws Exception {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /encoding/utf8 : Returns a UTF-8 encoded body.
     *
     * @return Encoded UTF-8 content. (status code 200)
     */
    @Operation(
        operationId = "encodingUtf8Get",
        summary = "Returns a UTF-8 encoded body.",
        tags = { "Response formats" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Encoded UTF-8 content.")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/encoding/utf8"
    )
    
    default ResponseEntity<Void> encodingUtf8Get(
        
    ) throws Exception {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /gzip : Returns GZip-encoded data.
     *
     * @return GZip-encoded data. (status code 200)
     */
    @Operation(
        operationId = "gzipGet",
        summary = "Returns GZip-encoded data.",
        tags = { "Response formats" },
        responses = {
            @ApiResponse(responseCode = "200", description = "GZip-encoded data.")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/gzip"
    )
    
    default ResponseEntity<Void> gzipGet(
        
    ) throws Exception {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /html : Returns a simple HTML document.
     *
     * @return An HTML page. (status code 200)
     */
    @Operation(
        operationId = "htmlGet",
        summary = "Returns a simple HTML document.",
        tags = { "Response formats" },
        responses = {
            @ApiResponse(responseCode = "200", description = "An HTML page.")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/html"
    )
    
    default ResponseEntity<Void> htmlGet(
        
    ) throws Exception {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /json : Returns a simple JSON document.
     *
     * @return An JSON document. (status code 200)
     */
    @Operation(
        operationId = "jsonGet",
        summary = "Returns a simple JSON document.",
        tags = { "Response formats" },
        responses = {
            @ApiResponse(responseCode = "200", description = "An JSON document.")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/json"
    )
    
    default ResponseEntity<Void> jsonGet(
        
    ) throws Exception {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /robots.txt : Returns some robots.txt rules.
     *
     * @return Robots file (status code 200)
     */
    @Operation(
        operationId = "robotsTxtGet",
        summary = "Returns some robots.txt rules.",
        tags = { "Response formats" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Robots file")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/robots.txt"
    )
    
    default ResponseEntity<Void> robotsTxtGet(
        
    ) throws Exception {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /xml : Returns a simple XML document.
     *
     * @return An XML document. (status code 200)
     */
    @Operation(
        operationId = "xmlGet",
        summary = "Returns a simple XML document.",
        tags = { "Response formats" },
        responses = {
            @ApiResponse(responseCode = "200", description = "An XML document.")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/xml"
    )
    
    default ResponseEntity<Void> xmlGet(
        
    ) throws Exception {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
